### ISSUE TITLE
Local issue with Language Setup > Introduction page

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#103]
I'm not sure if it is an issue of my local environment, but if I click on the Language Setup > Introduction page, the correct page is open but the left menu highlights the Getting Started with Webots > Introduction to Webots instead of the correct page.

I have this issue only when using the offline dock documentation widget.
I tested on the #102 branch.

**Comment by fabienrohrer** [comment]
I can reproduce. This is probably a bug in the pattern matching of the url: `introduction-to-webots` and the `introduction` pages are starting the same.

**Comment by omichel** [comment]
I confirm I can reproduce it as well.
