### ISSUE TITLE
Syntax highlighting broken on the Cyberbotics website

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#106]
The code should be highlighted when the markdown tags are referring to some language:

https://github.com/omichel/webots-doc/blob/master/guide/tutorial-4-more-about-controllers-20-minutes.md#program-a-controller
https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes#program-a-controller

This is working locally, but not on the Cyberbotics website.

Maybe it's due to #90!?

**Comment by fabienrohrer** [comment]
HTML tags are correctly generated.

**Comment by fabienrohrer** [comment]
From the JS debugger, it seems that `bootstrap.min.css` is overriding a lot of style info for the <pre><code> tags and descendant..

**Comment by fabienrohrer** [comment]
> HTML tags are correctly generated.

This is wrong, HTML tags are not well generated. The `<code>` tags should contain `language="..."` tags.

**Comment by omichel** [comment]
Also, something seems wrong in this page: https://github.com/omichel/webots-doc/blob/master/guide/tutorial-4-more-about-controllers-20-minutes.md#program-a-controller because only the last code section has proper syntax highlighting.

**Comment by fabienrohrer** [comment]
Well spotted, this is surely the point.

**Comment by fabienrohrer** [comment]
The reason of the issue is that the code which are not highlighted are into the scope of a comment in the MD file:

```
> **handson**:
Write the prototype of the `main()` function as follows:

>     // entry point of the controller
>     int main(int argc, char **argv)
>     { ...
```

While the syntax highlight is applied only when asking for it thanks to this syntax:

    ```c
    #include <webots/robot.h>
    #include <webots/differential_wheels.h>
    #include <webots/distance_sensor.h>

    // time in [ms] of a simulation step
    #define TIME_STEP 64

    // entry point of the controller
    int main(int argc, char **argv)
    { ...

https://raw.githubusercontent.com/omichel/webots-doc/master/guide/tutorial-4-more-about-controllers-20-minutes.md

**Comment by fabienrohrer** [comment]
The best solution is probably to indent the second syntax:
http://stackoverflow.com/questions/6235995/markdown-github-syntax-highlighting-of-code-block-as-a-child-of-a-list
Showdown seems to support this.

**Comment by fabienrohrer** [comment]
Showdown supports this for lists, but not for quotes, which seems to be a bug in showdown.

So we could:
- patch showdown accordingly
- implement this as a list, and put a special class on the `<li>` tag to display it in another way (as quotes or so):

    ```
    - **handson**:
        ```c
    void main() {}
        ```
    ```

- find custom way to implement this (not recommended)

Probably the second way is the best solution.
