### ISSUE TITLE
Missing final semi-colons in function definitions in the reference manual

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#120]
Because these final semi-colons are missing, the function on the second line is not properly syntax highlighted on github. See for example: https://github.com/omichel/webots-doc/blob/master/reference/robot.md (scroll down to wb_robot_step() function).

**Comment by fabienrohrer** [comment]
Well spotted.

**Comment by fabienrohrer** [comment]
Solving this improve also the syntax highlighter of Atom
