### ISSUE TITLE
Visualize branches from forked repositories

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#128]
It would be nice to be able to visualize branches from forked repositories (as users will have to fork the repository to contribute and will want to see the result before raising the thumb up on the pull request).

**Comment by fabienrohrer** [comment]
We could add a new GET arguments, like `?repository=remidhum`. Probably that the project name can also vary, so supporting something like `?repository=remidhum/my-custom-webots-doc-project-name` is probably required.

**Comment by DavidMansolino** [comment]
We could also support to specify the repository like this: `?version=repository:branch`
This way the user simply has to copy the `from` argument of the pull request (i.e. `remidhum:language_check` see PR #126).

**Comment by fabienrohrer** [comment]
Yes, this seems to be a better idea. Here too, probably that supporting a custom project name is required, so to summarize:

```
?version=[branch|tag]
?version=repository:[branch|tag]
?version=repository/custom-name:[branch|tag]
```

**Comment by DavidMansolino** [comment]
> Here too, probably that supporting a custom project name is required

I agree, by default when forking the name is the same, but the user is allowed to change it afterward.
What you propose seems good.

**Comment by omichel** [comment]
Done in #133.
