### ISSUE TITLE
Lost tag

### ISSUE THREAD

**Issue by remidhum** [omichel/webots-doc#151]
Upon changing or clicking on a new section in  [here] (https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects), the ID tag (i.e. `remidhum`) disappears. This causes some pages not to load up (`Advertising Board` in particular) and if refreshed, none of the pages load. 
However, as long as the page is not refreshed, the rest of the sections will correctly open even without the name tag. 

After a refresh (and a sub section change), the url is similar to this: 

> https://www.cyberbotics.com/doc/automobile/buildings?version=doc-automobile-objects

By adding `remidhum:` just after `version=` fixes the problem. 

> https://www.cyberbotics.com/doc/automobile/buildings?version=remidhum:doc-automobile-objects

**Comment by fabienrohrer** [comment]
The function forging the URLs is probably not taking into account the repo name.

**Comment by omichel** [comment]
Or the colon character  `:` should be escaped by using `%3A` instead.

**Comment by fabienrohrer** [comment]
The issue with advertising board seems unrelated: this link doesn't work in the omichel/master doc too: https://www.cyberbotics.com/doc/automobile/advertising-board

**Comment by fabienrohrer** [comment]
.. and locally too.

I get this error in the Java console:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by fabienrohrer** [comment]
LoL AdBlock is preventing to load the page, probably because of it's name :-D

**Comment by fabienrohrer** [comment]
If I rename the page to `ad-board.md` it is working. This is probably the best to do..

**Comment by fabienrohrer** [comment]
The `advertising` keyword should be prohibited. The file name and the file title should match. So I propose to rename this file and title to `Billboard`

**Comment by DavidMansolino** [comment]
Well spotted the AdBlock problem :smile:
