### ISSUE TITLE
Streaming documentation

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#166]
One can find only documentation about arguments of the streaming feature:

https://www.cyberbotics.com/doc/guide/starting-webots

Creating a section explaining at least:
- purpose of this feature
- where to find the streaming viewer page
- what can be streamed
- what are the limitations
- Links from `starting-webots` to this section, and vice versa.

**Comment by fabienrohrer** [comment]
.. and more:

- what is a animation, how to start it in a browser, what are the limitations.

**Comment by fabienrohrer** [comment]
I would propose to add the new section(s) in https://www.cyberbotics.com/doc/guide/development-environments

**Comment by omichel** [comment]
It doesn't seems to be related with a development environment... Maybe it's better to make a new chapter entitled "Web streaming".

**Comment by fabienrohrer** [comment]
Yes, it seems better.

**Comment by fabienrohrer** [comment]
.. or maybe a more generic chapter containing also "animation", "X3D", etc. as sections. Something like:

- "Simulation export"
    - "X3D"
    - "Web scene"
    - "Web animation"
    - "Web streaming"

**Comment by omichel** [comment]
Yes, that sounds good.

**Comment by fabienrohrer** [comment]
Implemented in #168
