### ISSUE TITLE
Joint schemas in doc

### ISSUE THREAD

**Issue by daniel-cyberbotics** [omichel/webots-doc#178]
_From @cypherluc on November 26, 2013 10:25_

In the reference manual, it would be nice to have schemas such as the one in the InsertNodeDialog depicting the joints visually.

_Copied from original issue: omichel/webots#84_

**Comment by daniel-cyberbotics** [comment]
Does the InsertNodeDialog still exists ?

**Comment by fabienrohrer** [comment]
> Does the InsertNodeDialog still exists ?

Yes, it's the dialog coming when pressing the "add button" from the scene tree view.
