### ISSUE TITLE
Too big images in user guide and reference manual

### ISSUE THREAD

**Issue by daniel-cyberbotics** [omichel/webots-doc#179]
_From @omichel on October 21, 2015 14:43_

In the user guide and reference manual, we should take care of the image sizes so that they display nicely on our web site without oversize problems like this: http://www.cyberbotics.com/guide/section2.3.php

It should be obvious to fix by adding an appropriate value to the `scale` field to the `graphic` node in the XML doc files.

_Copied from original issue: omichel/webots#3123_

**Comment by daniel-cyberbotics** [comment]
_From @fabienrohrer on February 2, 2016 10:50_

I just discovered the CSS `img { max-width: 80%; }` magic trick which set the image width to the image input dimension, with an upper bound set as a percent of the parent container.
e.g. http://omichel.github.io/webots-doc/index.html?book=guide&page=using-the-e-puck-robot.md

I propose to fix this only in the new documentation system.

**Comment by daniel-cyberbotics** [comment]
_From @fabienrohrer on February 16, 2016 15:20_

This will be fixed in the new documentation system

**Comment by daniel-cyberbotics** [comment]
_From @omichel on March 2, 2016 16:28_

See https://github.com/omichel/webots-doc/pull/1.

**Comment by fabienrohrer** [comment]
> This will be fixed in the new documentation system

It is fixed in the new documentation system. The images are bounded thanks to the CSS max-width feature. The images are also supporting well doc div resize.
