### ISSUE TITLE
User Guide 'Sample Webots Applications' chapter outdated

### ISSUE THREAD

**Issue by ghost** [omichel/webots-doc#181]
_From @DavidMansolino on January 27, 2016 8:49_

The user guide `Sample Webots Applications` (http://www.cyberbotics.com/guide/sample-webots-applications.php) chapter is largely outdated, a large number of samples are not included. Maybe once the new documentation system will be working it will be good to refactore it (add missing samples, replace pictures by x3d models /animations, etc.).

Samples (should be renamed `Demos`):
- missing anaglyph
- missing uneven_terrain
- order should be checked (should be order alphabetically to match order in the 'Open Sample World' window)

Devices:
- missing camera_auto_focus
- missing camera_compositors
- missing camera_noise_mask
- missing display
- missing force3d_sensor
- missing gyro
- missing hokuyo
- missing inertial_unit
- missing laser_pointer
- missing lidar
- missing position_sensor
- missing propeller
- missing receiver_noise
- missing sick
- missing spherical_camera
- missing supervisor
- missing track

Howto:
- missing asymmetric_friction1
- missing asymmetric_friction2
- missing center_of_mass
- missing contact_points
- missing cylinder_stack
- missing four_wheels
- missing gui_tracker
- missing omni_wheels
- missing passive_dynamic_walker
- missing pedal racer
- missing rope
- missing sick_terrain_scanning
- supervisor should be renamed `soccer_demo`
- missing vision
- missing ziegler_nichols

Geometries:
- missing capsule
- missing extended_solids
- missing extrusion
- missing floating_geometries
- missing high_resolution_indexedfaceset
- missing textured_boxes
- missing textured_proto_shapes

Missing `environments` category:
- indoor/apartment
- indoor/kitchen
- indoor/spinning_top (is this really the right location for this sample?)

The `mybot` directory is missing and seems redundant with the `devices` category.

The `Real Robots` part should be updated and is somehow redundant with the `Robots` chapter (http://www.cyberbotics.com/guide/robots.php).

_Copied from original issue: omichel/webots#3437_

**Comment by daniel-cyberbotics** [comment]
_From @fabienrohrer on January 27, 2016 10:21_

Yes, I think this will be better to solve after having switched to the new documentation. I expect that we will be able to create better pages (X3D export or so).

**Comment by stefaniapedrazzi** [comment]
I think we should take the time to fix the documentation of section for R2018a.
If it should be done manually we could also split the work and assign a folder to each developer.

**Comment by fabienrohrer** [comment]
:eyes:

**Comment by fabienrohrer** [comment]
I propose to do a set of very precise PR improving the sample chapter. The first ones would improve the existing sections individually (increase exhaustivity, remove useless info, etc.) targeting master, the second ones would have a higher level (change images to X3D scenes, uniformize the robots chapter) targeting develop.

**Comment by fabienrohrer** [comment]
Fixed :-)
