### ISSUE TITLE
Update User Guide screenshots showing Webots 7 version

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#200]
The screenshot `main_window.png` still shows the version Webots 7.3.0.

I don't think it is necessary to update the screenshots every minor version, but it would be better to do it every major version change.

**Comment by stefaniapedrazzi** [comment]
All the tutorials screenshots have to be updated as well.

It is a very bad advertising not having an up-to-date user Guide.

**Comment by fabienrohrer** [comment]
Not sure if this can work and is good looking, but maybe we could simply remove the window layout from the screenshots (at least the tutorial ones) in order to render them more time-persistent, and less OS dependent.

**Comment by stefaniapedrazzi** [comment]
You cannot make it completely OS dependent because of the fonts, etc. So if there is the window frame at least you understand why on a different platform you don't get the same result as in the screenshot.

Maybe it is not too bad.
But it's not big a work to update the screenshots.

**Comment by DavidMansolino** [comment]
Fixed in #380
