### ISSUE TITLE
Clang Static Analyser Result

### ISSUE THREAD

**Issue by daniel-cyberbotics** [omichel/webots-doc#211]
For information, the clang static analyse gave these issues:

---

**Dead store: Dead assignment: Value stored to 'det' is never read**
1: Value stored to 'det' is never read in /home/daniel/develop/webots/projects/robots/robotis-op2/libraries/robotis-op2/robotis/Framework/src/math/Matrix.cpp:100

---

**Memory Error: Memory leak: Potential leak of memory pointed to by 'protoList'**
 1: Assuming 'isValidProject' is 0 in /home/daniel/develop/webots/src/webots/app/WbApplication.cpp:266
 2: Memory is allocated in /home/daniel/develop/webots/src/webots/app/WbApplication.cpp:266

---

**Dead store: Dead assignment: Value stored to 'found' is never read**
 1: Value stored to 'found' is never read in /home/daniel/develop/webots/src/webots/core/WbMacAddress.cpp:121

---

**Logic error: Division by zero**
 1: Loop body executed 0 times in /home/daniel/develop/webots/src/webots/maths/WbMathsUtilities.cpp:274
 2: Division by zero in /home/daniel/develop/webots/src/webots/maths/WbMathsUtilities.cpp:303

---

**Dead store: Dead assignment: Value stored to 'max' is never read**
 1: Value stored to 'max' is never read in /home/daniel/develop/webots/src/webots/nodes/WbColor.cpp:45

---

**Logic error: Called C++ object pointer is null**
 1: Calling 'computePath' in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:96
 2: Passing value via 1st parameter 'node' in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:25
 3: Calling 'computePath' in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:25
 4: Assuming pointer value is null in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:58
 5: Loop body executed 0 times in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:58
 6: Loop body executed 0 times in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:72
 7: Called C++ object pointer is null in /home/daniel/develop/webots/src/webots/nodes/utils/WbUrl.cpp:78

---

**Logic error: Called C++ object pointer is null**
 1: Value assigned to field 'mField' in /home/daniel/develop/webots/src/webots/scene_tree/WbFieldEditor.cpp:198
 2: Assuming pointer value is null in /home/daniel/develop/webots/src/webots/scene_tree/WbFieldEditor.cpp:209
 3: Calling 'WbFieldEditor::computeFieldInformation' in /home/daniel/develop/webots/src/webots/scene_tree/WbFieldEditor.cpp:214
 4: Called C++ object pointer is null in /home/daniel/develop/webots/src/webots/scene_tree/WbFieldEditor.cpp:276

**Comment by omichel** [comment]
This issue should be moved to the `webots` repository. It is not related with `webots-doc`.

**Comment by daniel-cyberbotics** [comment]
This issue was moved to omichel/webots#4382
