### ISSUE TITLE
External URL doesn't open from Webots offline documentation

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#352]
When clicking on an external URL in the offline Webots documentation nothing happens.
I have this issues at least on Linux.

For example:
User Guide -> Language Setup ->  Using ROS -> "Willow Garage" link at the end of the first paragraph.
https://github.com/omichel/webots-doc/blob/master/guide/using-ros.md#what-is-ros

On the cyberbotics website and on GitHub it works correctly.

**Comment by fabienrohrer** [comment]
I can reproduce on macOS.
