### ISSUE TITLE
Use master as the default branch instead of gh-pages

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#36]
Now that have a nice online viewer allowing us to visualize easily any branch, I believe there is no need to maintain this `gh-page` branch as the default branch. We should use the `master` branch instead.

**Comment by fabienrohrer** [comment]
I just created the master branch.

Here is the TODO list to complete this task:

- [ ] @omichel Set the master branch as the default branch in this repo preferences
- [ ] @omichel Remove the github.io interface from this repo preferences (I think we enabled something)
- [ ] Retarget all the current PRs (could be done later, when needed)
- [ ] @me Remove the gh-branch

**Comment by fabienrohrer** [comment]
..and:

- [ ] @me Fix the references to gh-pages in this repo
- [ ] @me Fix the README file

**Comment by fabienrohrer** [comment]
.. and:

- [ ] @me Fix the wiki

**Comment by omichel** [comment]
I cannot remove the github.io interface from this repo preferences. Here is what I see:
![github](https://cloud.githubusercontent.com/assets/1264964/14915857/4378af42-0e16-11e6-81ea-d3cfa771f61c.png)

Do you have any idea on how to proceed?

**Comment by fabienrohrer** [comment]
This is maybe simply because the gh-pages page is existing. I would say we should try this later.

**Comment by omichel** [comment]
Ok.

**Comment by fabienrohrer** [comment]
I removed the `gh-pages` branch. What is the status of the preferences?

**Comment by omichel** [comment]
They also disappeared from the settings. Great. :smile:

**Comment by omichel** [comment]
I believe we are done with this one.

**Comment by fabienrohrer** [comment]
Probably just one thing remaining; did you also updated viewer.js on the FTP?

**Comment by omichel** [comment]
This is done.
