### ISSUE TITLE
Exporting meshes 

### ISSUE THREAD

**Issue by remidhum** [omichel/webots-doc#386]
Upon exporting an IndexedFaceSet from Webots to Blender the following distortion occurs:

![comparison](https://user-images.githubusercontent.com/20298915/28012638-b606f124-6566-11e7-8b4a-add6939c27f5.png) 

Where the Left sphere is the result of the Webots export and the Right one the original.

When importing the mesh from blender the sphere looks fine:

![asis](https://user-images.githubusercontent.com/20298915/28012668-d9e87040-6566-11e7-8b57-cfb3bccc0b6c.png)

But once the mesh is exported the faces seem to warp.

Crease angle values and triangulating the faces in blender before exporting to Webots yields the same problem.

**Comment by tn12787** [comment]
Shouldn't this be in the main Webots repo?

**Comment by remidhum** [comment]
yes sorry
