### ISSUE TITLE
TTF fonts on mac

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#402]
In https://github.com/omichel/webots/pull/5667 I had to workaround a bug in QtWebKit about the support of CSS font-face.

It could be good to check if Qt > 5.9 solves this.

**Comment by fabienrohrer** [comment]
Fixed in https://github.com/omichel/webots-doc/pull/494

**Comment by omichel** [comment]
@fabienrohrer: Can we close this one as well (we don't use Raleway any more)?

**Comment by fabienrohrer** [comment]
I think it would be better to keep it open, it's the only trace we have about the fact that the fonts are buggy on macOS, and that we have a fallback for this.
The long term solution is probably to upgrade to QtWebEngine which hopefully supports better fonts.

**Comment by fabienrohrer** [comment]
Fixed in omichel/webots#7316
