### ISSUE TITLE
Review controller code snippets

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#44]
I noticed that most of the code snippets uses the following form without checking for the ``wb_robot_step`` return value:

```
while(1) {
  ..
  wb_robot_step(TIME_STEP);
  ..
}
```

An the ``wb_robot_cleanup`` is not used, at least in the Controller Programming section.

Wouldn't be better to improve the examples in order to show to the users the correct way to implement their controller?

**Comment by fabienrohrer** [comment]
Sure, it seems better to propose a single and simple way to program the controllers.

**Comment by omichel** [comment]
Done in #45.
