### ISSUE TITLE
Missing variable description about Webots Makefile

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#469]
In https://github.com/omichel/webots-doc/blob/master/guide/using-webots-makefiles.md we are not explaining the purpose of the following variables (which are explained in the default Makefile):
  - LFLAGS
  - QT
  - VERBOSE

The `LFLAGS` variable is very similar to the `LIBRARIES` one, but I believe it is good to keep them separated in order to better make a distinction between libraries and other flags: 
```
###-----------------------------------------------------------------------------
### Rule to make the executable file from C/C++ objects
###-----------------------------------------------------------------------------
$(BUILD_GOAL_DIR)/$(MAIN_TARGET): $(OBJECTS) $(LINK_DEPENDENCIES)
	@echo "# linking" $(notdir $@)
	$(SILENT)$(LINKER) $(LFLAGS) -o $@ $(OBJECTS) $(LIBRARIES)
```

Furthermore, for `CFLAGS` and `INCLUDE` we give the exact same explanation: `Specifies a list of flags that will be passed to the gcc/g++ compiler`. We should explain in which case use which one.

**Comment by fabienrohrer** [comment]
The improvement proposals seems good to me.
