### ISSUE TITLE
Obsolete 'Sensor rays shape' and 'RGB sensitive' in DifferentialWheels doc

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#482]
In the Physics VS Kinematics mode table of the DifferentialWheels node:
  https://www.cyberbotics.com/doc/reference/differentialwheels#differentialwheels-simulation-modes
There are a `Sensor rays shape` and a `RGB sensitive` entries, this doesn't seem related to the differentialWheels node and is probably obsolete.

Can we remove these two lines?

**Comment by omichel** [comment]
Yes, I believe we should remove them.

**Comment by DavidMansolino** [comment]
Fixed in #484
