### ISSUE TITLE
Fix Objects PROTO description in automobile doc

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#505]
In the Road PROTO description it is not very clear why some fields are not listed in the PROTO  declaration with blue background:
https://www.cyberbotics.com/doc/automobile/road-segments
https://github.com/omichel/webots/blob/develop/projects/objects/road/protos/Road.proto
https://github.com/omichel/webots/blob/develop/projects/objects/road/protos/StraightRoadSegment.proto

The idea could be to not rewrite the fields of the base class.
But at the moment it is not clear if this is made on purpose or a bug because the approach is not consistent and it is only applied for some parameters.
For example:
* `id`, `startJunction`,  `endJunction`, and `name` are not duplicated in the StraightRoadSegment description
* `translation`, `rotation`, `width`, `rightBorder`, and `locked` are written in the Road description and in the StraightRoadSegment description.

**Comment by DavidMansolino** [comment]
I will make it consistent and not rewrite the fields of the base class as we are doing in the reference manual.

**Comment by DavidMansolino** [comment]
Fixed in #524
