### ISSUE TITLE
Improve documentation on how to change Python version on Linux

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#525]
We should add some documentation explaining how users have to change the default python version on Linux to make it work with Webots.

For example if in my terminal I set an alias:
```
alias python=python3
```
when typing `python --version` I'm getting 3.4.3 but if from the same terminal I start Webots, then Python 2.7.6 is still used.

**Comment by stefaniapedrazzi** [comment]
Actually this seems more a bug than a documentation issue...

**Comment by omichel** [comment]
Yes, we should probably parse the alias list searching for the python command to handle this case. I will open a new PR for that.

**Comment by stefaniapedrazzi** [comment]
I think that the problem is that the context in which Webots/python is executed is not the one set by the user.

**Comment by omichel** [comment]
Not sure to understand why you mean here... My plan was to execute the alias command from Webots with the python command as an argument to check whether it's an alias or not. If it's an alias, we would replace the actual python command by its aliased value.

**Comment by stefaniapedrazzi** [comment]
In Webots you execute `python -c "import sys; print(sys.version)"` in a QProcess.
It should already call the alias if the Webots context is correctly matching the terminal context from which it is executed.

**Comment by stefaniapedrazzi** [comment]
Ok, but you use this only to get the version and for starting the controller.

**Comment by omichel** [comment]
Unfortunately, it doesn't seem possible to retrieve the aliases of a bash from a binary program launched from this bash. One way could be to use a script to launch webots and the script would pass the aliases to Webots. However, this is pretty tricky and complicated to implement, especially on Windows...

**Comment by stefaniapedrazzi** [comment]
Ok.
I think it is fine to keep it like this, but at least on Ubuntu we should provide the documentation about how the user has to change the python version using `update-alternatives`.

**Comment by omichel** [comment]
`update-alternatives` is the wrong way to change the python version:
https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3/321000#321000?newreg=68c519da67844f30b8e61cff813f385a

**Comment by stefaniapedrazzi** [comment]
At the moment it is the only working way.
And I don't have any issue with that.

**Comment by stefaniapedrazzi** [comment]
The other alternative that I didn't test yet is a python virtual environment.

**Comment by stefaniapedrazzi** [comment]
Running Webots in a python virtual environment works also correctly.

**Comment by omichel** [comment]
We could also add a Preferences items that contains the default python command (that would be used instead of "python" unless something else is provided in the `runtime.ini` file of a controller).

**Comment by stefaniapedrazzi** [comment]
Yes, this is also ok.
The important thing is that the chosen solution is well documented.
