### ISSUE TITLE
Link on the same page working only first time [Firefox]

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#55]
If you go to this page: https://www.cyberbotics.com/doc/reference/accelerometer and click on one of the `Accelerometer` links, it work fine (position modified and url changed to https://www.cyberbotics.com/doc/reference/accelerometer#accelerometer) but then if you press again on a `Accelerometer` links it doesn't do anything.

Note that I was able to reproduce this on Firefox (Linux) but on Chrome everything is working fine.

**Comment by fabienrohrer** [comment]
👀

**Comment by fabienrohrer** [comment]
I can reproduce this.
