### ISSUE TITLE
Missing text in FAQ

### ISSUE THREAD

**Issue by fzimmerm** [omichel/webots-doc#552]
Under the [General FAQ](https://www.cyberbotics.com/doc/guide/general-faq), there is the following phrase

> 2. The controller process has vanished from the Task Manager (Windows) or is shows as when using ps -e (Linux/Mac).

It seems some text is missing, and _is_ should probably read _it_.

**Comment by omichel** [comment]
@fzimmerm: feel free to open a new PR for that and submit a possible correction.

**Comment by fzimmerm** [comment]
Fixed in https://github.com/omichel/webots-doc/pull/553
