### ISSUE TITLE
Review HTML / JS / CSS modifications as close as possible from production state

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#554]
Discussion started from here #542

Goal: Find a way to test HTML /JS / CSS modifications as close as possible from the production state.

**Comment by fabienrohrer** [comment]
Olivier proposes:

> I believe that a solution that relies on https://rawgit.com to refer to our github branch files should be investigated, so that we can review such PRs without any risk of breaking our deployed code.

**Comment by fabienrohrer** [comment]
[Fiddler](https://www.telerik.com/download/fiddler) seems to be a convenient tool to solve this issue.

**Comment by omichel** [comment]
I would prefer to avoid using commercial tools. Our need is very simple and could certainly be fulfilled with some open source piece of software.

**Comment by fabienrohrer** [comment]
Yes, I agree. I'm exploring a solution with creasemonkey and tampermonkey first.

**Comment by fabienrohrer** [comment]
greasemonkey doesn't have the exact goal we aim (It's very good to inject JS into a production page, but not much. CSS and simple JS file replacement are not obvious. The fact that doc is written in PHP doesn't help too.).

I just discuss with Olivier, and we will test to modify doc.php to be able to test the JS and the CSS of  a branch, as we do for MD files. It seems to be simple to setup.
