### ISSUE TITLE
Hyperlinked code conflicts

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#556]
When code is hyperlinked, it is displayed as code, but not as hyperlinked. cf. #555

Example:

```
[`test`](http://google.ch)
```

We have to decide what to do with this case.

The current situation has some sense, it seems to me that changing the priority of style application will lead other issues, and mixing these 2 styles would complexify the doc understanding.

I think a better solution would be to strictly forbid this case in the tests.

**Comment by omichel** [comment]
@fabienrohrer: Can we close this issue?

**Comment by fabienrohrer** [comment]
Yes, thank you.
