### ISSUE TITLE
Wrong information in documentation of wb_supervisor_simulation_reset_physics

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#571]
In the documentation of the `wb_supervisor_simulation_reset_physics` function we say:
> Furthermore, this function resets the seed of the random number generator used in Webots, so that noise-based simulations can be be reproduced identically after calling this function.

But this is not true:
https://github.com/omichel/webots/blob/dc02d43eb6744886e20710a64346152ac3c536e2/src/webots/nodes/WbSupervisor.cpp#L390
https://github.com/omichel/webots/blob/dc02d43eb6744886e20710a64346152ac3c536e2/src/webots/app/WbApplication.cpp#L345

Should we correct the documentation or the implementation?
To me it seems better to correct the documentation, because the seed should be reset only when reverting (but I am not 100% convinced).

**Comment by omichel** [comment]
I agree with you: we should fix the documentation.

**Comment by DavidMansolino** [comment]
Fixed in #572
