### ISSUE TITLE
Improve node fields blocks

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#586]
Some node fields definition with long comments look bad:
https://www.cyberbotics.com/doc/reference/worldinfo?version=develop

Before we only had this issue on small screens but now limiting the maximum width of the page this happens independently from the web page size.

**Comment by fabienrohrer** [comment]
This is slightly related with : https://github.com/omichel/webots-doc/issues/180

I would propose to:
1. replace the `# .*` sentences by a format indicating only the range and units when applicable, for example: `# unit: [m/s] - range: (0, inf)`
2. to add hyperlinks from the fields to their description.

**Comment by fabienrohrer** [comment]
For now the node description are simply code, but it would be certainly better to have a custom MD extension for this, for example:

```md
%node

Cone {
  SFFloat [bottomRadius](#bottomRadius) 1 # [m] - (0,inf)
  SFFloat [height](#height) 2 # [m] - (0,inf)
  SFBool [side](#side) TRUE
  SFBool [bottom](#bottom) TRUE
  SFInt32 [subdivision](#subdivision) 12 # (3,inf)
}

%end
```

**Comment by fabienrohrer** [comment]
Or better, something which could be simply parse by a regex:

%node "Cone"
SFFloat | bottomRadius | 1 | [m] - (0,inf)
SFFloat | height | 2 | [m] - [m] - (0,inf)
SFBool | side | TRUE | [m] - N/A
SFBool | bottom | TRUE | [m] - N/A
SFFloat | subdivision | 12 | [m] - (3,inf)
%end

showdown could generate an HTML tree for this, and the CSS could display it nicely.

**Comment by omichel** [comment]
(note: instead of N/A in that case, I would rather display TRUE/FALSE).

**Comment by tn12787** [comment]
I prefer the first solution to the second, I feel it's overkill to introduce a really complex format for something we don't necessarily need yet.

**Comment by tn12787** [comment]
We also will need to add anchors for every field descriptor.

**Comment by tn12787** [comment]
For a first step I have manually improved the node blocks, adding uniform descriptors for the values that can be inserted in each field.

**Comment by fabienrohrer** [comment]
The general issue is explained there: #180
The original issue about long comments has been fixed.
