### ISSUE TITLE
The Master Snapshot from the RawGit CDN will never refresh.

### ISSUE THREAD

**Issue by tn12787** [omichel/webots-doc#589]
https://github.com/rgrove/rawgit/issues/41

We need instead of loading just the page from the master branch (which is cached one and NOT flushable as described in the link above) we need some kind of unique identifier to get the version of the file we actually want.

I propose adding the master branch's HEAD commit SHA in order to create the unique URL. This way changes merged to master will actually make the page update.

**Comment by fabienrohrer** [comment]
This is correct, I slightly misuse rawgit CDN: referring the branch is a bad solution.
