### ISSUE TITLE
Navigator back button misbehaving

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#590]
While browsing the user guide or reference manual online, the back button of the browser doesn't behave as expected (seems doing nothing). This is a very bad user experience and may also badly affect our google ranking.

**Comment by fabienrohrer** [comment]
It seems to be reproductible only when navigating from a node (let say [Camera](https://www.cyberbotics.com/doc/reference/camera)) to the other APIs by clicking on the `{C++}, {Java}, {Python}, {Matlab}, {ROS}` links).

It seems the link is copied twice in the browser history, implying it's impossible to get back (it would require to skip two levels):

![capture d ecran 2018-02-07 a 10 45 25](https://user-images.githubusercontent.com/866788/35909517-344801e8-0bf4-11e8-9ffe-96b797c1fab5.png)

The same occurs locally.
