### ISSUE TITLE
Language APIs docs are not user friendly

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#591]
The description of API functions in different languages is not easy to understand for new users. We should setup a new system to improve that.

For example, each function could be presented under a tab row that would allow the user to select among C, C++, Python, Java, MATLAB, ROS. The tab selection of the user should be stored (in the browser cookie for example) so that it becomes the default tab selected.

I believe this could be handled by some Javascript code that will manage the tabs, perform some search and replace in the text (to replace a C function name by a C++ method name) and display the needed text sections.

**Comment by tn12787** [comment]
Could we not use some sort of templating for this?

Something like:

```jsx
<p>The function {{functionName}} resets the simulation immediately...</p>
```

**Comment by omichel** [comment]
Yes, except that in some language it's called a method rather than a function and also we want to be able to refer to other functions/methods... So, I would rather formulate it like:
```html
<p>The {{function:wb_distance_sensor_enable}} shall be called before any subsequent call to the {{funtion:wb_distance_sensor_get_value}}.</p>
```
That could translate into:

> The `wb_distance_sensor_enable` function shall be called before any subsequent call to the `wb_distance_sensor_get_value` function.

Or:

> The `enable` method should be called before any subsequent call to the `getValue` method.

**Comment by fabienrohrer** [comment]
Alternatively or parallelly, it would be good to add conditions on the language, somehting like this:

```
{{ if language == 'Python' then }}
> Note **Python**: blah blah
{{ end }}
```

**Comment by stefaniapedrazzi** [comment]
Also note that having the list of all the available functions at the beginning of the node page (as we have now for the other APIs) is very useful. I would keep it and add all the description later like in the Qt documentation or in all the other automatically generated standard documentation.

**Comment by omichel** [comment]
In that case we could simply recognize the "Note **LANGUAGE**:" template and use it to hide or show the note depending on the selected tab.

**Comment by fabienrohrer** [comment]
The Atom documentation provides a very nice example: there are OS tabs (windows, etc.); selecting them is adding an anchor (a GET parameter would be better for us) and is displaying the requested documentation:

https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-mac

**Comment by DavidMansolino** [comment]
The ` Improve this page` button of the Atom doc is interesting too. When you click on it, instead of pointing to the root of the github project, it directly points to the fork and edition of the correct page (e.g. https://github.com/atom/flight-manual.atom.io/edit/master/content/getting-started/sections/installing-atom.md which points directly to your forked project once you have forked it) maybe we could do the same for our `Contribute on GitHub!` button.

**Comment by fabienrohrer** [comment]
(automatic close)

**Comment by DavidMansolino** [comment]
Note that after #831 there is a probably unwanted impact on this page: https://www.cyberbotics.com/doc/guide/using-ros

**Comment by fabienrohrer** [comment]
Well spotted. I'm fixing this right now.
