### ISSUE TITLE
Bold text are not displayed as bold on Chrome

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#602]
cf. Keywords and menus

Chrome:

![capture d ecran 2018-02-08 a 09 42 56](https://user-images.githubusercontent.com/866788/35963248-766c186e-0cb4-11e8-9df0-9dbe70b01503.png)

Firefox:

![capture d ecran 2018-02-08 a 09 42 56 2](https://user-images.githubusercontent.com/866788/35963249-769dd462-0cb4-11e8-809d-abf01c9d7f57.png)

**Comment by tn12787** [comment]
This would appear to be a bug on chromne on macOS with some fonts.

On firefox & safari on macOS, everything is fine.

On windows, on Chrome & firefox, everything is fine.

On Ubuntu 16.04, on chrome and firefox, everything is fine.

I propose we close this issue as I don't think it's our fault.
