### ISSUE TITLE
Long code in table can goes out of the cell

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots-doc#644]
See: https://www.cyberbotics.com/doc/automobile/openstreetmap-importer

Working fine in Github viewer: https://github.com/omichel/webots-doc/blob/master/automobile/openstreetmap-importer.md

**Comment by tn12787** [comment]
https://www.cyberbotics.com/doc/automobile/openstreetmap-importer?version=fix-table-code-problems
