### ISSUE TITLE
Embed youtube videos in user guide and reference manual

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#667]
It would be nice to embed youtube videos in the user guide and reference manual, especially on robot pages and howto pages. For example a video like https://www.youtube.com/watch?v=vFwNwT8dZTU is very good for presenting the youBot robot.

This is used in the unreal documentation pages like this one: https://docs.unrealengine.com/latest/INT/Engine/Rendering/LightingAndShadows/LitTranslucency/index.html

Generally, we should use as much pictures and videos as possible: if a picture says a thousand words, a video says a thousand pictures 😉. Most of the popular Webots videos we created should be somehow integrated into our user guide or reference manual.

**Comment by tn12787** [comment]
This is already technically possible due to the `showdown-youtube` extension we added for the blog to be able to show the robotbenchmark video :smile:. I'm looking forward to saying a million words at a time :fireworks:

**Comment by fabienrohrer** [comment]
I will include the robot movies we have on youtube in https://github.com/omichel/webots-doc/pull/665

**Comment by fabienrohrer** [comment]
Fixed in #682
