### ISSUE TITLE
Use X3D interactive models to document robot actuators

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#668]
Instead of using pictures and tables like in https://www.cyberbotics.com/doc/guide/using-the-aibo-ers7-robot we should use X3D interactive models to document robot actuators position and range (mainly motors and leds) like in: https://www.cyberbotics.com/files/repository/x3dom/darwin-op/soccer.html

However, the X3D interactive model should be normalized the following way:
- it should display only the robot (not other object, no floor) on a white background.
- the list of motors should be exhaustive and refer to the device names.
- the range of the motors should be displayed on the slider (for unlimited ranges of rotational motors, we should simply allow -&pi; &harr; &pi; animation)
- for leds, we should either use a color slider (for RGB led) or a simple toggle for standard leds.

Therefore, we should stop creating images like:
![image](https://user-images.githubusercontent.com/1264964/36836065-7cd577ec-1d38-11e8-92cb-a762c5e719cc.png)
and corresponding tables as they will be discarded when using the X3D interactive models.

**Comment by fabienrohrer** [comment]
I agree.
I think it doesn't change the short term priorities I have, i.e., to create better robot images, as in https://github.com/omichel/webots-doc/pull/665. These images can be replaced by this new system later.

**Comment by DavidMansolino** [comment]
Implemented in #800
