### ISSUE TITLE
Rename 'ms' argument in sensor enable functions

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#67]
Rename the ``ms`` argument to `sampling_rate``, for all the sensors, and to indicate that its unit is in milliseconds in the comments. => The argument name should describe its purpose, not its unit.

**Comment by omichel** [comment]
We should apply the same to the `wb_robot_step()` where the `ms` argument should be renamed to `duration`.

**Comment by omichel** [comment]
What is the best, `sampling_rate` or `sampling_period`? We seems to use sampling period in our explanations and API, see: https://www.cyberbotics.com/doc/reference/accelerometer#wb_accelerometer_enable so it would be more consistent to use `sampling_period`. Do you agree?

**Comment by stefaniapedrazzi** [comment]
Yes, ``sampling_period`` is fine for me.

**Comment by DavidMansolino** [comment]
I think `sampling_period` is clearly better than `sampling_rate` as a period is expressed in `s` (or eventually `ms`) and a rate is expressed in Hz.

**Comment by omichel** [comment]
Fixed in #137.
