### ISSUE TITLE
Mathematical functions

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#7]
For now, the formula sources are still into the TEX format in the `webots/src/doc/formulas/` repository.

A better integration seems obviously required.

Several Javascript are doing mathematical text to HTML formula view conversion very well including:
- [MathJax](https://www.mathjax.org/)
- [AsciiMath](http://asciimath.org/)

MathJax is supposed to support TEX formulas, amongs other, which seems to be the shortest way to import our formulas.

Some code snippet are existing to integrate this into showdown:
https://gist.github.com/xentec/6588519
https://gist.github.com/npisenti/3028983

**Comment by fabienrohrer** [comment]
Complete review of Markdown and mathematical topic: https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by fabienrohrer** [comment]
@omichel After our discussion on Monday, I'm assigning this issue to you.

**Comment by omichel** [comment]
The proposed solution is the following:
- use MathML in our source files.
- include the MathJax Javascript from the cdn for the online version with the `MML_HTMLorMML` config, which mean input is in MathML format, output is in HTML or MathML if supported by the browser (Firefox supports MathML, Chrome doesn't).
- the offline version relies on WebKit which supports natively MathML.
- we can use online wysiwyg tools to generate the formulae in MathML format such as http://www.wiris.com/editor/demo/en/mathml-latex

**Comment by fabienrohrer** [comment]
Fixed in https://github.com/omichel/webots-doc/pull/41
