### ISSUE TITLE
Improve the layout

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#76]
Then if the left menu area is small the section titles are not included in the menu gray area (see BallJointParameter section title in the following screenshot):
![6c52d12c-2e23-11e6-8636-de9b681f3599](https://cloud.githubusercontent.com/assets/1264964/15970296/36df1f52-2f34-11e6-8156-e9792d147cd5.png)
Additionally if the documentation widget width is small the up, left and right arrow icons overlap.

The position of the horizontal scrollbar is a little bit weird if the page content is short.
I would probably expect it to be in any case at the bottom of the widget instead of at the end of the page content:
![dd59bff8-2e27-11e6-933c-c9813f9c1940](https://cloud.githubusercontent.com/assets/1264964/15970309/4a81b4ac-2f34-11e6-807d-52e01b43c806.png)

**Comment by stefaniapedrazzi** [comment]
Same issue with the text width not matching the background box in the pink area.

**Comment by stefaniapedrazzi** [comment]
Other issue:

If the documentation widget width is small the navigation arrows in the left menu overlaps.
![doc-layout-issue](https://cloud.githubusercontent.com/assets/5910449/15998950/89d6f27e-3142-11e6-8a3e-564bef4066c4.png)

**Comment by stefaniapedrazzi** [comment]
To make the documentation widget usable given the small space we have now using a dock widget, we should make the left menu width manually resizeable and add the possibility to completely hide it.

**Comment by omichel** [comment]
Fixed in #102.
