### ISSUE TITLE
Load CSS and JS dependencies dynamically from a file

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#778]
viewer.js, the CSS and the MD files are loaded dynamically depending on the branch.

But it's not the case for the JS and CSS dependencies which are hard-coded:

https://github.com/omichel/webots-doc/blob/master/index.html#L6
https://github.com/omichel/webots-doc/blob/master/index.html#L39
https://github.com/omichel/webots-doc/blob/master/doc.php#L66

This is extremely annoying for testing in production modifications on these dependencies (update, addition, removal) slowing a lot the workflow.

I'm wondering if we could add them to a file and load them dynamically from webots.js.

**Comment by omichel** [comment]
I believe it's not a good design template to perform dynamic includes in Javascript... Can't we imagine another solution for that? For example, replacing `index.html` with `index.php` that would load the correct resources.

**Comment by fabienrohrer** [comment]
PHP is only working on the website, but not locally when embedded in Webots. Moreover it seems annoying to run a PHP server to test locally.

**Comment by omichel** [comment]
For the local version, the index.html should anyhow include only on the dependencies installed locally, so no other version than the current local version is supported, so that should not be not a problem to have static includes there.

**Comment by fabienrohrer** [comment]
A solution could be a tradeoff:

- Create a `dependencies.txt` file containing the CSS and JS deps.
- doc.php reads this file to build dynamically the HTML tree.
- `local_exporter.py` could generate index.html (git ignored) from index.template.html and `dependencies.txt` => it seems `local_index.html` is not required anymore (webots should refer to `index.html`.
