### ISSUE TITLE
Unneded vertical scrollbar for images

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#787]
When opening the offline User Guide in Webots, I see a vertical scrollbar for the image.
This is not always visible but depends on the width of the documentation.

![offline_guide](https://user-images.githubusercontent.com/5910449/38859151-aec38cde-422d-11e8-9ac9-95453f4803e0.png)

**Comment by omichel** [comment]
Your screenshot did not upload properly...

**Comment by stefaniapedrazzi** [comment]
Now it is. I had to upgrade firefox.

**Comment by tn12787** [comment]
With any width of documentation I can't reproduce this on Ubuntu 16.04 in Webots nor locally on Firefox :disappointed:

**Comment by tn12787** [comment]
Never mind, I managed to get it to flash once or twice in the embedded doc.

**Comment by stefaniapedrazzi** [comment]
Note that this is exclusively reproducible in the offline documentation in Webots.
And only for images without caption.

**Comment by stefaniapedrazzi** [comment]
I have it both in Ubuntu 14.04 and Ubuntu 16.04.
