### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#8]
Similarily to #7, the diagram sources are still into the DIA format in the `webots/src/doc/dia/` repository.

Here too, a better integration seems to be required.

This issue aims to report the best candidates to do so.

**Comment by omichel** [comment]
We could take inspiration from Stakedit which support both maths (MathJax) and diagrams / flowcharts https://stackedit.io/editor and provide a nice online editor (which we could use to edit our documentation). It's fully open source (Apache license) and it looks like the ultimate goal to provide a nice user interface to edit our documentation.

**Comment by stefaniapedrazzi** [comment]
Not all the current dia files contain diagrams or graphs.
Do you suggest to simply discard them and keep only the PDF and PNG images for these images?

**Comment by fabienrohrer** [comment]
> We could take inspiration from Stakedit which supports both maths (MathJax)

Oops, I read this slightly too late, I started (and almost completed) the implementation of the mathematical formulas using MathJax only: #9
But this is probably a very good intermediate state, because StackEdit is using the same syntax I choose to include maths: https://stackedit.io/editor#mathjax

**Comment by omichel** [comment]
> Not all the current dia files contain diagrams or graphs.
> Do you suggest to simply discard them and keep only the PDF and PNG images for these images?

No, it that case, we should keep the dia source files, so that anybody can edit them easily and produce new PDF/PNG images if needed.

**Comment by DavidMansolino** [comment]
Implemented in #674
