### ISSUE TITLE
Tutorial 4 of Webots Documentation requires adjustment

### ISSUE THREAD

**Issue by mramused** [omichel/webots-doc#801]
As per image, the documentation needs the addition of a line that instructs users to define SPEED_UNIT otherwise program will return an error.

#define SPEED_UNIT 1
![speed_unit error](https://user-images.githubusercontent.com/19386384/39131702-a238eca8-46ff-11e8-9d79-a66cdd120e67.jpg)

**Comment by fabienrohrer** [comment]
Thank you for this report.

SPEED_UNIT can be simply dropped.

**Comment by fabienrohrer** [comment]
Thank you, this has been fixed in https://github.com/omichel/webots-doc/pull/802 and already in production: https://www.cyberbotics.com/doc/guide/tutorial-4-more-about-controllers-20-minutes#the-controller-code

**Comment by mramused** [comment]
Brilliant, thanks :)
