### ISSUE TITLE
Update Screenshots to use new GUI for R2018b

### ISSUE THREAD

**Issue by tn12787** [omichel/webots-doc#810]
Before releasing R2018b we should update our screenshots for Webots Night.

**Comment by fabienrohrer** [comment]
This issue should be fixed at the last minute before releasing. Several issues are still susceptible to change slightly the GUI.

**Comment by DavidMansolino** [comment]
Images to update (mandatory):
  - references/add_proto.png
  - guide/main_window.png
  - guide/rendering_device_window.png
  - guide/scene_tree1.png
  - guide/speedometer.png
  - guide/text_editor.png
  - guide/tutorial_appearance.png
  - guide/tutorial_ball.png
  - guide/tutorial_def_use.png
  - guide/tutorial_dumbbell.png
  - guide/tutorial_gui.png
  - guide/tutorial_walls.png
  - We should add the context menu in one of the screenshot

Optionnal:
  - guide/make_movie_dialog.png
  - guide/screenshot-html-export-dialog.png
  - guide/streaming-server-screenshot.png

**Comment by DavidMansolino** [comment]
Since we have no issue related to the gui anymore I think the images can know be updated, does someone see a reason for postponing the update?

**Comment by omichel** [comment]
I believe we can go ahead with that.

**Comment by stefaniapedrazzi** [comment]
I think that also these two images showing the field editor needs to be updated:

references/scene_tree_with_proto.png
guide/field_editor.png

**Comment by DavidMansolino** [comment]
Fixed in #911.
