### ISSUE TITLE
Hashtag links are broken on Firefox/Windows

### ISSUE THREAD

**Issue by omichel** [omichel/webots-doc#816]
https://www.cyberbotics.com/doc/guide/robotis-op2#symmetry-wbt doesn't scroll down to the tag and the index links are broken.

I believe this was broken recently it was working when @DavidMansolino posted this: https://www.cyberbotics.com/forum?message=8064

Maybe it was broken by #800?

**Comment by stefaniapedrazzi** [comment]
I also noticed this morning on Linux/Firefox with:
https://www.cyberbotics.com/doc/guide/using-python#use-an-alternative-python-version

But on my Linux/Chrome it works correctly.

**Comment by fabienrohrer** [comment]
I have the same on macOS, this is working on Chrome, but not on Firefox.

**Comment by omichel** [comment]
By saving a doc page (see attachment) and analyzing it with https://validator.w3.org I found several errors that may explain the problem, in particular "Error: Attribute name not allowed on element h2 at this point.".

[doc.zip](https://github.com/omichel/webots-doc/files/1966193/doc.zip)

**Comment by omichel** [comment]
Apparently hashtag links should refer to the `id` attribute in HTML5, not to the `name` attribute, which is obsolete in HTML5. See last answer of https://stackoverflow.com/questions/25813113/what-is-the-usage-of-the-name-attribute-in-h1-h6-tags

**Comment by fabienrohrer** [comment]
The reason of the original issue is that wwi.css (which had been introduced with the robot component) is modifying `body.scroll-behavior`: https://github.com/omichel/webots/blob/master/resources/web/wwi/wwi.css#L2
Modifying body or any tag without using class or ids is a very bad practice because it render any CSS unmodular.
