### ISSUE TITLE
Wrong highlighting of MATLAB section title

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#850]
![matlab_section_title](https://user-images.githubusercontent.com/5910449/40823273-17af0a92-6570-11e8-977e-359058d30529.png)

**Comment by fabienrohrer** [comment]
Fixed in https://github.com/omichel/webots-doc/pull/841 (OO tags have been dropped)

**Comment by fabienrohrer** [comment]
Fixed in #841
