### ISSUE TITLE
Node enumeration lists are not up-to-date

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#851]
As mentioned [here](https://github.com/omichel/webots-doc/pull/841#discussion_r192152786) by Stefania, node enumeration lists are not up-to-date (`WB_NODE_ACCELEROMETER`, etc.). It would be good to redo exhaustive lists and determine if tests would help in this case.

From Stefania:

> missing:
> - WB_NODE_LENS
> - WB_NODE_LENS_FLARE
> - WB_NODE_MUSCLE
> - WB_NODE_MULTI_TEXTURE
> - WB_NODE_COMPOSED_CUBE_MAP_TEXTURE
> - WB_NODE_COMPOSED_SHADER
> - WB_NODE_SKIN
> - WB_NODE_UNIFORM
>
> to be removed:
> - WB_LENS_DISTORTION

**Comment by fabienrohrer** [comment]
The situation is even worst: nodes.h and derived files are not updated.
I propose to do first a hot-fix of the doc to let match the doc with the true state of node.h and to fix it in a cleaner way both in webots@master and develop for the next releases.

**Comment by stefaniapedrazzi** [comment]
We should improve the way we list the nodes in the documentation.
Currently they copy-pasted from the node.h, but the order doesn't make sense for users.
It would be much better to use a clear and simple listing order, for example the alphabetical one.

Also note that we should only list the documented nodes and not experimental or not supported node (for example SKIN, SWITCH, etc.)

**Comment by fabienrohrer** [comment]
Fixed
